const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const cors = require('cors')
const router = express.Router()
const passport = require('passport')

app.use(bodyParser.json())
app.use(cors())
app.use(bodyParser.urlencoded({ extended: false }))
app.use('/', router)
app.use('', require('./routes/courses_route'))
app.use('', require('./routes/users_route'))
app.use(passport.initialize())
require('./config/passport')(passport)
app.listen(8000)
console.log('Listening to PORT 8000')